  services: 
    backend:
      build:
        context: ./backend
      ports:
        - "5001:5001"
      networks:
        - mern-network
      

    frontend: 
      build: 
        context: ./frontend
      ports:
        - "8001:8001"
    
    mongo:
      image: mongo:latest
      command: mongodb --port 27018
      profiles:
      - debug  # <--- This container is now EXCLUDED by default
      ports:
        - "27018:27017"
      networks:
        - mern-network
      
  networks:
    mern-network:
      driver: bridge
