   services: 
    backend:
      build:
        context: ./backend
      ports:
        - "5001:5001"
      networks:
        - mern-network
      

    frontend: 
      build: 
        context: ./frontend
      ports:
        - "8001:80"
    
    mongo:
      image: mongo:latest
      ports:
        - "27018:27018"
      networks:
        - mern-network
      
  networks:
    mern-network:
      driver: bridge
